### ISSUE TITLE
Grabar discos

### ISSUE THREAD

**Issue by lsl1005** [lsl1005/GESPRO_GESTIONTAREAS#38]
Código fuente app
    Ejecutable app
    Herramientas
        Plataforma de desarrollo del algoritmo
        Herramienta de conteo de abejas
    Documentación
        Memoria
        Anexos
        JavaDoc
    Dataset de videos

README

    Repositorio GoBees
    Repositorio prototipos
    Repositorio dependencia OpenCV

**Comment by JGD1017** [comment]
Grabados y duplicados como backup
